import type { Db, Tx } from "@repo/db";
import {
  denominations,
  denominationSkills,
  municipalities,
  skillGroups,
  skills,
} from "@repo/db/schema";
import { and, eq, inArray } from "drizzle-orm";

import { toSearchText } from "./text";

/**
 * The seed pipeline: authored reference data in the repository, loaded into the database, **safe to
 * run again**.
 *
 * Idempotence is not a nicety here. `pnpm db:seed` runs on every `pnpm bootstrap`, on every
 * `pnpm db:reset`, and in the deploy right after `pnpm db:migrate` (ADR-0022) — so a second run has
 * to be a no-op, and a changed label has to be an update rather than a duplicate. The natural key is
 * the **slug** for a term and the **DIVIPOLA code** for a municipality, never the `bigint` id, which
 * is exactly why ADR-0003 gave reference tables `GENERATED BY DEFAULT` identities.
 *
 * Two things this deliberately does **not** do:
 *
 * - **It never deletes a term.** A Skill missing from the seed is left alone, because retirement is
 *   a decision someone makes (ADR-0012) and a deletion here would silently strip skills from
 *   published profiles the moment somebody tidied a data file.
 * - **It never invents a slug.** The seed carries the slug it authored, so renaming a term in the
 *   data file changes what a person reads and not what a URL or a Publication points at. Only
 *   `authorSkill` derives a slug, because there a term is being created for the first time.
 *
 * `search_text` is computed here, in application code, by the same normaliser used on every other
 * write — ADR-0014 as amended by ADR-0031.
 */

export interface SkillGroupSeed {
  slug: string;
  name: string;
  /** Browse order (ADR-0023's secondary path). Alphabetical is not the order we want. */
  position: number;
}

export interface SkillSeed {
  slug: string;
  name: string;
  group: string;
  cuocCode?: string;
}

export interface DenominationSeed {
  slug: string;
  name: string;
  /** Slugs of the Skills this title implies. They must be in the same seed. */
  implies: readonly string[];
  cuocCode?: string;
}

export interface MunicipalitySeed {
  /** DANE DIVIPOLA, five digits, leading zero included. */
  divipolaCode: string;
  name: string;
  departmentCode: string;
  departmentName: string;
  latitude: number;
  longitude: number;
}

export interface CatalogSeed {
  skillGroups: readonly SkillGroupSeed[];
  skills: readonly SkillSeed[];
  denominations: readonly DenominationSeed[];
  municipalities: readonly MunicipalitySeed[];
}

export interface SeedCount {
  inserted: number;
  updated: number;
  unchanged: number;
}

export interface SeedReport {
  skillGroups: SeedCount;
  skills: SeedCount;
  denominations: SeedCount;
  /** Links added and links removed — a Denomination's bundle is replaced, not merged. */
  denominationSkills: { linked: number; unlinked: number };
  municipalities: SeedCount;
}

const emptyCount = (): SeedCount => ({ inserted: 0, updated: 0, unchanged: 0 });

/**
 * A DIVIPOLA code is five digits and its first two are the department's. Checked here rather than
 * trusted, because the whole location model — ADR-0014's three tiers — is an equality on those two
 * digits, and a typo would put a municipality in a department it is not in.
 */
function assertMunicipality(row: MunicipalitySeed): void {
  if (!/^\d{5}$/.test(row.divipolaCode)) {
    throw new Error(`"${row.divipolaCode}" (${row.name}) is not a DIVIPOLA code: five digits.`);
  }
  if (!row.divipolaCode.startsWith(row.departmentCode) || row.departmentCode.length !== 2) {
    throw new Error(
      `${row.name}: DIVIPOLA ${row.divipolaCode} does not start with department code ` +
        `"${row.departmentCode}".`,
    );
  }
  // Colombia sits between roughly 4°S and 13°N, 67°W and 82°W. The bound is loose on purpose: it is
  // here to catch a swapped pair or a dropped minus sign, not to validate cartography.
  if (row.latitude < -5 || row.latitude > 14 || row.longitude > -66 || row.longitude < -83) {
    throw new Error(
      `${row.name}: (${String(row.latitude)}, ${String(row.longitude)}) is not in Colombia — ` +
        "latitude and longitude are probably swapped.",
    );
  }
}

/**
 * Load the authored catalog, idempotently.
 *
 * The caller owns the transaction (ADR-0006): this takes a `Db | Tx` and never opens one, so the
 * CLI can wrap the whole seed in a single transaction and a test can roll it back.
 */
export async function seedCatalog(db: Db | Tx, seed: CatalogSeed): Promise<SeedReport> {
  for (const row of seed.municipalities) assertMunicipality(row);

  const report: SeedReport = {
    skillGroups: emptyCount(),
    skills: emptyCount(),
    denominations: emptyCount(),
    denominationSkills: { linked: 0, unlinked: 0 },
    municipalities: emptyCount(),
  };

  // --- Skill Groups -------------------------------------------------------------------------
  const existingGroups = new Map(
    (
      await db
        .select({
          id: skillGroups.id,
          slug: skillGroups.slug,
          name: skillGroups.name,
          position: skillGroups.position,
        })
        .from(skillGroups)
    ).map((row) => [row.slug, row]),
  );

  for (const group of seed.skillGroups) {
    const existing = existingGroups.get(group.slug);
    if (!existing) {
      await db.insert(skillGroups).values(group);
      report.skillGroups.inserted += 1;
      continue;
    }
    if (existing.name === group.name && existing.position === group.position) {
      report.skillGroups.unchanged += 1;
      continue;
    }
    await db
      .update(skillGroups)
      .set({ name: group.name, position: group.position })
      .where(eq(skillGroups.id, existing.id));
    report.skillGroups.updated += 1;
  }

  const groupIds = new Map(
    (await db.select({ id: skillGroups.id, slug: skillGroups.slug }).from(skillGroups)).map(
      (row) => [row.slug, row.id],
    ),
  );

  // --- Skills -------------------------------------------------------------------------------
  const existingSkills = new Map(
    (
      await db
        .select({
          id: skills.id,
          slug: skills.slug,
          name: skills.name,
          searchText: skills.searchText,
          skillGroupId: skills.skillGroupId,
          cuocCode: skills.cuocCode,
        })
        .from(skills)
    ).map((row) => [row.slug, row]),
  );

  for (const skill of seed.skills) {
    const skillGroupId = groupIds.get(skill.group);
    if (skillGroupId === undefined) {
      throw new Error(
        `Skill "${skill.slug}" names Skill Group "${skill.group}", which is not seeded.`,
      );
    }
    const wanted = {
      name: skill.name,
      searchText: toSearchText(skill.name),
      skillGroupId,
      cuocCode: skill.cuocCode ?? null,
    };
    const existing = existingSkills.get(skill.slug);
    if (!existing) {
      await db.insert(skills).values({ slug: skill.slug, ...wanted });
      report.skills.inserted += 1;
      continue;
    }
    if (
      existing.name === wanted.name &&
      existing.searchText === wanted.searchText &&
      existing.skillGroupId === wanted.skillGroupId &&
      existing.cuocCode === wanted.cuocCode
    ) {
      report.skills.unchanged += 1;
      continue;
    }
    // `is_retired` and `superseded_by_id` are untouched on purpose: retirement is a decision made
    // through `retireSkill`, and a re-run of the seed must not quietly bring a term back.
    await db.update(skills).set(wanted).where(eq(skills.id, existing.id));
    report.skills.updated += 1;
  }

  const skillIds = new Map(
    (await db.select({ id: skills.id, slug: skills.slug }).from(skills)).map((row) => [
      row.slug,
      row.id,
    ]),
  );

  // --- Denominations, and the bundles they imply ---------------------------------------------
  const existingDenominations = new Map(
    (
      await db
        .select({
          id: denominations.id,
          slug: denominations.slug,
          name: denominations.name,
          searchText: denominations.searchText,
          cuocCode: denominations.cuocCode,
        })
        .from(denominations)
    ).map((row) => [row.slug, row]),
  );

  for (const denomination of seed.denominations) {
    const wanted = {
      name: denomination.name,
      searchText: toSearchText(denomination.name),
      cuocCode: denomination.cuocCode ?? null,
    };
    const existing = existingDenominations.get(denomination.slug);
    let denominationId: bigint;

    if (!existing) {
      const [row] = await db
        .insert(denominations)
        .values({ slug: denomination.slug, ...wanted })
        .returning({ id: denominations.id });
      if (!row)
        throw new Error(`Seeding the Denomination "${denomination.slug}" inserted nothing.`);
      denominationId = row.id;
      report.denominations.inserted += 1;
    } else {
      denominationId = existing.id;
      if (
        existing.name === wanted.name &&
        existing.searchText === wanted.searchText &&
        existing.cuocCode === wanted.cuocCode
      ) {
        report.denominations.unchanged += 1;
      } else {
        await db.update(denominations).set(wanted).where(eq(denominations.id, existing.id));
        report.denominations.updated += 1;
      }
    }

    const wantedSkillIds = denomination.implies.map((slug) => {
      const id = skillIds.get(slug);
      if (id === undefined) {
        throw new Error(
          `Denomination "${denomination.slug}" implies Skill "${slug}", which is not seeded.`,
        );
      }
      return id;
    });

    const linked = new Set(
      (
        await db
          .select({ skillId: denominationSkills.skillId })
          .from(denominationSkills)
          .where(eq(denominationSkills.denominationId, denominationId))
      ).map((row) => row.skillId),
    );

    const toLink = wantedSkillIds.filter((id) => !linked.has(id));
    if (toLink.length > 0) {
      await db
        .insert(denominationSkills)
        .values(toLink.map((skillId) => ({ denominationId, skillId })));
      report.denominationSkills.linked += toLink.length;
    }

    // A link the seed no longer claims is removed. That is not a deletion of vocabulary — the Skill
    // and the Denomination both survive; what changes is which Skills the title offers to add.
    const wantedLinks = new Set(wantedSkillIds);
    const toUnlink = [...linked].filter((id) => !wantedLinks.has(id));
    if (toUnlink.length > 0) {
      await db
        .delete(denominationSkills)
        .where(
          and(
            eq(denominationSkills.denominationId, denominationId),
            inArray(denominationSkills.skillId, toUnlink),
          ),
        );
      report.denominationSkills.unlinked += toUnlink.length;
    }
  }

  // --- Municipalities ------------------------------------------------------------------------
  const existingMunicipalities = new Map(
    (
      await db
        .select({
          id: municipalities.id,
          divipolaCode: municipalities.divipolaCode,
          name: municipalities.name,
          searchText: municipalities.searchText,
          departmentCode: municipalities.departmentCode,
          departmentName: municipalities.departmentName,
          latitude: municipalities.latitude,
          longitude: municipalities.longitude,
        })
        .from(municipalities)
    ).map((row) => [row.divipolaCode, row]),
  );

  for (const municipality of seed.municipalities) {
    const wanted = {
      name: municipality.name,
      searchText: toSearchText(municipality.name),
      departmentCode: municipality.departmentCode,
      departmentName: municipality.departmentName,
      latitude: municipality.latitude,
      longitude: municipality.longitude,
    };
    const existing = existingMunicipalities.get(municipality.divipolaCode);
    if (!existing) {
      await db
        .insert(municipalities)
        .values({ divipolaCode: municipality.divipolaCode, ...wanted });
      report.municipalities.inserted += 1;
      continue;
    }
    if (
      existing.name === wanted.name &&
      existing.searchText === wanted.searchText &&
      existing.departmentCode === wanted.departmentCode &&
      existing.departmentName === wanted.departmentName &&
      existing.latitude === wanted.latitude &&
      existing.longitude === wanted.longitude
    ) {
      report.municipalities.unchanged += 1;
      continue;
    }
    await db.update(municipalities).set(wanted).where(eq(municipalities.id, existing.id));
    report.municipalities.updated += 1;
  }

  return report;
}
