import { readFileSync, writeFileSync } from "node:fs";

/**
 * The second half of `pnpm --filter @repo/auth generate-schema`.
 *
 * **Better Auth's Drizzle generator emits `timestamp('x')` for every date column and offers no
 * option to change it** — `generate-drizzle-schema-*.mjs` has the string hardcoded per dialect, with
 * `pg` mapped to a bare `timestamp` and no `withTimezone` anywhere in the package. ADR-0008 is
 * unconditional the other way: *"`timestamptz` for every instant. Never bare `timestamp`."*
 *
 * The three ways out, and why this is the one:
 *
 * - **Accept the bare columns.** Rejected. The rule exists because the database session timezone is
 *   never to be relied upon (ADR-0008), and `sessions.expires_at` is compared to `now()` on every
 *   authenticated request. It happens to be harmless while everything runs UTC, which is exactly the
 *   kind of "harmless until it moves" this repository writes rules to avoid.
 * - **Hand-write the four tables.** Rejected by ADR-0003: it means owning `users`, `sessions`,
 *   `accounts` and `verifications` through every Better Auth upgrade, in the area the audit found
 *   undocumented, to win columns no domain query touches.
 * - **Rewrite the generator's output, in the same command that generates it.** This. The file stays
 *   generator-*derived* rather than hand-edited: nobody is ever asked to remember the edit, because
 *   re-running `generate-schema` reapplies it. A hand-edit would be reverted by the next `generate`
 *   with no diff for anyone to notice, which is the failure mode the audit warns about.
 *
 * It also prepends the header that says all of the above at the top of the file people actually
 * open, and it is **strict**: an emission shape it does not recognise fails the command rather than
 * writing a file that quietly no longer satisfies ADR-0008.
 */

const path = process.argv[2];
if (!path) {
  throw new Error("usage: normalise-generated-schema.ts <path-to-generated-schema>");
}

const source = readFileSync(path, "utf8");

/**
 * `timestamp("created_at")` → `timestamp("created_at", { withTimezone: true })`.
 *
 * Anchored on the closing paren so a call that already carries options is left alone and counted
 * separately below — the day the generator grows a `{ mode }` argument, this notices instead of
 * silently skipping the column.
 */
const WITHOUT_OPTIONS = /\btimestamp\((['"][a-z_]+['"])\)/g;

const normalised = source.replace(WITHOUT_OPTIONS, "timestamp($1, { withTimezone: true })");

const rewritten = (source.match(WITHOUT_OPTIONS) ?? []).length;
if (rewritten === 0) {
  throw new Error(
    `${path}: no bare timestamp() call found. Either the generator learned about time zones — in ` +
      `which case delete this script — or its output shape changed and this rewrite is now a no-op ` +
      `silently leaving ADR-0008 unsatisfied.`,
  );
}

/** Any `timestamp(...)` this rewrite did not touch, so an unrecognised shape is loud. */
const remaining = normalised.match(/\btimestamp\((?![^)]*withTimezone)/g);
if (remaining) {
  throw new Error(
    `${path}: ${String(remaining.length)} timestamp() call(s) left without withTimezone. The ` +
      `generator emitted a shape this script does not recognise; widen the pattern rather than ` +
      `editing the generated file.`,
  );
}

const HEADER = `/**
 * **Generated by \`pnpm --filter @repo/auth generate-schema\`. Do not edit.**
 *
 * \`auth generate\` is a whole-file overwrite for Drizzle and never a merge, so a hand-edit here is
 * reverted by the next run with no diff anyone reads. Better Auth owns these four tables
 * (ADR-0003); our own tables live in their own files beside this one, and drizzle-kit diffs both.
 *
 * One thing here is *not* the generator's: every \`timestamp\` carries \`withTimezone\`, applied by
 * \`scripts/normalise-generated-schema.ts\` in the same command, because the generator hardcodes a
 * bare \`timestamp\` and ADR-0008 requires \`timestamptz\` for every instant. That script explains
 * why it is a rewrite rather than an edit.
 *
 * The \`relations()\` exports below are generated too and are **deliberately not re-exported** from
 * \`schema/index.ts\`: nothing uses them, \`experimental.joins\` is off, and the generator names them
 * \`sessionss\`/\`accountss\`.
 */
`;

writeFileSync(path, `${HEADER}${normalised}`, "utf8");

process.stdout.write(`${path}: ${String(rewritten)} timestamp column(s) given withTimezone\n`);
