import { defineConfig } from "oxfmt";

/**
 * Formatting for the whole repo, from one file. Unlike `oxlint.config.mts` there is no
 * per-workspace counterpart: `format` is a root script rather than a turbo task, because a
 * formatter has nothing to gain from the package graph — it reads files, not dependencies.
 *
 * `.mts` for the same reason the oxlint config is: the root `package.json` has no
 * `"type": "module"`, so Node would parse a `.ts` config as CommonJS, hit ESM syntax, and reparse
 * it with a warning on every run. It sits outside every `tsconfig.json` `include`, so
 * `check-types` does not cover it — `defineConfig` is what type-checks it, in the editor.
 *
 * Everything else is oxfmt's defaults on purpose, including `printWidth: 100`. Prettier ran here
 * with no config at all, so its 80 was never a decision anyone made; 100 is what the prose in
 * `docs/` is already hand-wrapped to. `sortImports` is oxfmt's own extension and stays off —
 * changing formatter and import order in one motion would leave nobody able to say which tool
 * moved a line.
 */
export default defineConfig({
  // oxfmt reads `.gitignore` on its own, so this list is only what git still tracks or leaves
  // untracked but visible.
  ignorePatterns: [
    // Vendored skill documentation, fetched by `skills add`. `skills-lock.json` stores a hash of
    // each file, so reformatting one would report the skill as tampered with.
    ".agents/**",
    // Agent scratch: skill symlinks and full worktree copies of this repo.
    ".claude/**",
    // Working research notes, not repo prose.
    ".research-25/**",
    // Generated by pnpm; enormous, and no one reads it.
    "pnpm-lock.yaml",
    // drizzle-kit owns these — the SQL, and the snapshots plus `_journal.json` it rewrites on
    // every `db:generate`. CLAUDE.md forbids hand-editing them, and a formatter is a hand.
    "packages/db/migrations/**",
  ],
});
