import { bigint, timestamp, uuid } from "drizzle-orm/pg-core";
import { v7 as uuidv7 } from "uuid";

/**
 * ADR-0008's conventions, as spreadable helpers — so that violating one takes **deliberately not
 * using** a helper. The ADR is the rationale; this file is the rule.
 *
 * `casing: "snake_case"` is set once in `drizzle.config.ts` and once in `client.ts`, so nothing
 * here names a column twice: TypeScript reads `createdAt`, Postgres reads `created_at`.
 */

/**
 * The primary key of a domain entity — `BIGINT GENERATED ALWAYS AS IDENTITY` (ADR-0003).
 *
 * Half the width of a UUID in every foreign key and index, and it inserts sequentially. It is also
 * why nothing outside the database may use it: a sequential key leaks row counts and invites
 * enumeration, which is what `publicId()` is for.
 */
export const id = () => bigint({ mode: "bigint" }).generatedAlwaysAsIdentity().primaryKey();

/**
 * The primary key of a **reference** table seeded from external data — `GENERATED BY DEFAULT`,
 * because a DIVIPOLA municipality or a taxonomy row needs an explicit id at insert time
 * (ADR-0003).
 */
export const seededId = () =>
  bigint({ mode: "bigint" }).generatedByDefaultAsIdentity().primaryKey();

/**
 * The identifier anything outside the system uses (ADR-0003). **Not every table gets one** — only
 * rows addressed from outside, such as `persons`, `publications` and `offers`. A municipality is
 * addressed by its DANE code and a join table is never addressed at all.
 *
 * Generated in application code rather than by a Postgres extension (ADR-0003), so it behaves
 * identically in Postgres, in PGlite — whose extension set is limited — and in a unit test with no
 * database at all. `uuid`'s implementation also keeps a sequence counter, so two ids minted inside
 * the same millisecond still sort in the order they were made; that is the property the unique
 * index on `public_id` is being bought.
 */
export const publicId = () => uuid().notNull().unique().$defaultFn(uuidv7);

/** `timestamptz`, never bare `timestamp`. Every instant in this schema is one. */
const instant = (name?: string) => timestamp(name as never, { withTimezone: true });

/**
 * `created_at` and `updated_at`, for a table whose rows change.
 *
 * `updated_at` is maintained by Drizzle's `$onUpdate()` rather than a Postgres trigger: a trigger
 * is genuinely stronger, but drizzle-kit does not manage triggers, so each one would be
 * hand-written SQL inside a migration — cutting against drizzle-kit as sole owner of migrations
 * (ADR-0004).
 */
export const timestamps = () => ({
  createdAt: instant().notNull().defaultNow(),
  updatedAt: instant()
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

/**
 * `created_at` alone, for an **append-only** table — `consents`, `document_versions`.
 *
 * The *absence* of `updated_at` is the marker of an append-only table, which is why this is a
 * separate helper rather than a flag on `timestamps()`: choosing append-only is then a visible act
 * at the table definition, and an `updated_at` on a table nobody updates is a lie that invites an
 * `UPDATE`.
 */
export const createdAt = () => ({ createdAt: instant().notNull().defaultNow() });

// **`personRef()` is in `schema/people.ts`, not here, and the move is a finding rather than a
// preference.** ADR-0008 and `docs/module-package-recipe.md` both place it in this file. Written
// here it needs `import { persons } from "./schema/people"` at module scope — and every table file
// imports *this* module, so the cycle `columns.ts` → `schema/people.ts` → `columns.ts` is entered
// from whichever side loads first. Drizzle's `references()` callback is lazy and survives that, but
// `id()` and `timestamps()` are called while `people.ts` is still evaluating, and drizzle-kit's
// esbuild bundle fails outright: `ReferenceError: Cannot access 'id' before initialization`.
//
// Beside the table it names, there is no cycle and nothing to be careful about — and a caller
// needing the helper is already importing that file for the table itself.
