CREATE TABLE "denomination_skills" (
	"denomination_id" bigint NOT NULL,
	"skill_id" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "denomination_skills_denomination_id_skill_id_pk" PRIMARY KEY("denomination_id","skill_id")
);
--> statement-breakpoint
CREATE TABLE "denominations" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "denominations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"search_text" text NOT NULL,
	"is_retired" boolean DEFAULT false NOT NULL,
	"superseded_by_id" bigint,
	"cuoc_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "municipalities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "municipalities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"divipola_code" text NOT NULL,
	"name" text NOT NULL,
	"search_text" text NOT NULL,
	"department_code" text NOT NULL,
	"department_name" text NOT NULL,
	"latitude" double precision NOT NULL,
	"longitude" double precision NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "skill_groups" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "skill_groups_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"position" integer NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "skills" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "skills_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"search_text" text NOT NULL,
	"skill_group_id" bigint NOT NULL,
	"is_retired" boolean DEFAULT false NOT NULL,
	"superseded_by_id" bigint,
	"cuoc_code" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "denomination_skills" ADD CONSTRAINT "denomination_skills_denomination_id_denominations_id_fk" FOREIGN KEY ("denomination_id") REFERENCES "public"."denominations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denomination_skills" ADD CONSTRAINT "denomination_skills_skill_id_skills_id_fk" FOREIGN KEY ("skill_id") REFERENCES "public"."skills"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "denominations" ADD CONSTRAINT "denominations_superseded_by_id_denominations_id_fk" FOREIGN KEY ("superseded_by_id") REFERENCES "public"."denominations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "skills" ADD CONSTRAINT "skills_skill_group_id_skill_groups_id_fk" FOREIGN KEY ("skill_group_id") REFERENCES "public"."skill_groups"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "skills" ADD CONSTRAINT "skills_superseded_by_id_skills_id_fk" FOREIGN KEY ("superseded_by_id") REFERENCES "public"."skills"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "denomination_skills_skill_id_idx" ON "denomination_skills" USING btree ("skill_id");--> statement-breakpoint
CREATE UNIQUE INDEX "denominations_slug_unique" ON "denominations" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "denominations_search_text_trgm_idx" ON "denominations" USING gin ("search_text" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "denominations_superseded_by_id_idx" ON "denominations" USING btree ("superseded_by_id");--> statement-breakpoint
CREATE UNIQUE INDEX "municipalities_divipola_code_unique" ON "municipalities" USING btree ("divipola_code");--> statement-breakpoint
CREATE INDEX "municipalities_search_text_trgm_idx" ON "municipalities" USING gin ("search_text" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "municipalities_department_code_idx" ON "municipalities" USING btree ("department_code");--> statement-breakpoint
CREATE UNIQUE INDEX "skill_groups_slug_unique" ON "skill_groups" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "skills_slug_unique" ON "skills" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "skills_search_text_trgm_idx" ON "skills" USING gin ("search_text" gin_trgm_ops);--> statement-breakpoint
CREATE INDEX "skills_skill_group_id_idx" ON "skills" USING btree ("skill_group_id");--> statement-breakpoint
CREATE INDEX "skills_superseded_by_id_idx" ON "skills" USING btree ("superseded_by_id");